name: Build and Release Engine

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Compile and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Build Linux Binary
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
          go build -o entropy-key-scanner-linux-amd64 ./cmd/engine/main.go

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            entropy-key-scanner-linux-amd64
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}